### ISSUE TITLE
Logstash is not able to parse CW logs

### ISSUE THREAD

**Issue by joykabir** [threadwaste/logstash-codec-cloudwatch_logs#2]
Hi,

I have setup a ELK stack to inject CW logs via Kinesis stream. I can see input/output data in Kinesis stream. However I can see (or guess) Logstash cannot parse CW logs.

As you know CW logs are compressed to gzip level6 and then sent to Kinesis. 
### An example of CW log look like below:
{
    "name": String,
    "message": {
        "subscriptionBucket": String,
        "MaxKeys": Int,
        "subscriptionFolder": String,
        "axbucket": String,
        "subscriptionEvent": String
    },
    "hostname": String,
    "pid": 1,
    "level": "INFO",
    "msg": "Config object",
    "time": "2016-11-25T08:09:40.888Z",
    "v": 0
}
### Error in logstash.log:
{:timestamp=>"2016-11-25T07:15:53.604000+0000", :message=>"Error processing record: Input length = 1", :level=>:error}

### Logstash config file
ubuntu@ip-172-31-34-1:~$ cat /etc/logstash/conf.d/logstash-indexer.conf 
input {
    kinesis {
        kinesis_stream_name => 'elastic-XXX'
        application_name => 'elastic-DynamoDBTable-XXX'
        region => 'eu-west-1'
	codec => cloudwatch_logs
    }
}

output {
    elasticsearch { hosts => ["localhost:9200"] }
    stdout { codec => rubydebug }
}

Any help would be appreciated. Thanks //Ziaul

**Comment by threadwaste** [comment]
@joykabir Are you using >= 2.0.1 of the Kinesis input plugin? [This PR](https://github.com/logstash-plugins/logstash-input-kinesis/pull/3) is required for it to work with this codec.

**Comment by joykabir** [comment]
@threadwaste: Yes plugin logstash-input-kinesis>2 and logstash >2

**Comment by threadwaste** [comment]
@joykabir So, this error:

```{:timestamp=>"2016-11-25T07:15:53.604000+0000", :message=>"Error processing record: Input length = 1", :level=>:error}```

...is the result of the Kinesis input plugin attempting to decode gzipped content as a UTF-8 string. That behavior was changed in versions of that input plugin >= 2.0.1 specifically to enable this codec. Perhaps a gist of `logstash-plugin list --verbose`, and a gist of your Logstash starting up with --verbose would be helpful.

**Comment by gregorycox** [comment]
Your changes referenced above about >=2.0.1 of the kinesis input plugin, should be =2.0.1, not >=, your changes don't exist in 2.0.2, and 2.0.3

https://github.com/logstash-plugins/logstash-input-kinesis/blob/v2.0.2/lib/logstash/inputs/kinesis/worker.rb

**Comment by threadwaste** [comment]
Feel free to revitalize if necessary, but this appears to outside of this codec.
